sudo: required
services:
  - docker

env:
  global:
    - IMAGE_NAME=breedbase/pg
    - secure: Mx7ZGpd+pQArABcBS5ZA4s26imqrQ9D1khA3xwMbEkhEltHnYknGQqE/ggNIYlKsqndmJ182vnjitLtWlMG04S6fsKQeXC6eaNEdjBCXf77lFfCy3ItndoyS3McfAGthERryseDfv5gnl153RD0P1bZ1+rFh8m+QLO0iMYSCvdWel87ccV9MhErtkNrQN/AmCa9BJ4UN0933/HCueIfVi2VGWcGG+xsMgu7n5f9bM9nSFFPWNfe3eK6gFsqD4MKbvza/RHiboA5rZIZTF9J0V2LGK2scdIxD7ZfRN0DLqTKCzyaVuQHoUiXjeq4qjsfC/31z3UpSMFzdIG48NMoXZixzab98vckuI63PRTt65hmbFghKGJHrgFT12w4ha1y+LdvT2NnIXPkrNm6IR+0jwhoHPLCFZL2ALZPHDPVu2bcUS5j/lPm2iBxUhT3xQ+d18BquWUlbH81JAGPFNPoXbiLu5vzV+DMssl6vZJjGXFrBTvpoIBFfvKijnH5+tcovhjP+YOrLlo7bYDhlfPLm08piZv30cbG1D45wAfpBLeON/ApT1RqPKAlHFo4hUYYwr91V0O48sMU5qOUkTlnwhg2ka8feRfJGp957gRJEOuIHTqcV5lG7icmab5u/OYXpKD9mgG2zC/XxWm9DOLFMXTAkh5+S2JNT/EA2f6m13EI=
    - secure: OYMt7+/YiYrBWgv342958sTGYHfeY7UsmYZ63sPiFCSz74Y1CsgFoHvhymHegac1FthaItuHrjnWqVvx+AstIY7RSjC7tdlawyhBbqm2LNWhqYbcRYf2KuVArzxdWZPdYH4vOESZRyP+tX3p4ozIXF5ZcRgBITHC6ADAR6Tqwjr3Rb8xkRIrIsWrCaNL9csA/FQwsOMQg/tG/dpQUfOaLyJuSFg9H61b04hh71zmHpkof3KiRhY/0k081FnPY8/z1+ZJJIyk3E/J3n0Iftchkyf/DkmffJkYNOG8Vip30A1a4AkXF2opuRy08BuXcjmMdYqHobGRCXVzt0JCBBdPZ9fL6reBbJak6dNQBcf3alkNxkgjxQfUYt5jvddcdG5uaVgfcC0660DYEA/Nxj62yKEoVr1KiW3PytZcUm+xRoba4s3MDvZlMxjYXD3DuSQbqy9WqEIQsF+S5cnQaWPB9sVBUTqvjUAaFO3e+QasdILNdl2AMBexabSfK/J1OF2xkKPQ+OTOqVaeeqvTPVqWap/t5boYpG8B185ZMWQtBLF8xM2pAzY/vTRJDP/zG/9ZPcISlmaqYpeVGPiZi2eQU6BnzgRnuPfShCW5LyygU+YKl/+V8boSrF0gl/ziz+vYBh5v2jy1Gs9h/FY4ud10GYYwltDcfizOzVk6ct+L1bc=

branches:
  only:
    - master

before_script:
  - docker pull "$IMAGE_NAME" || true

script:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

after_script:
  - docker images

before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_BUILD_NUMBER}"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_BUILD_NUMBER}"
  on:
    branch: master