env:
  - secure: "lGiGg0NxXFlaxIB7xzHmzKgF9zhbva8Fihm/hyLmWNRgbRcyAoz0Zck5ozGDkWXldLv1sWyyOQ7zmHu1DjtjinuHrNp7sOzOOQrCaamAxt5i/Xdk43Cgyu9R5uW2d5PvXMGYxhGGz2GDyih57ZXasJS0gx7LFXXRtmJkE4Sb1qhlzxCDQUOqiI/iTZ9hPqwxyaHCgbvA016yXI2hosZ3aiUC7w2lx0zNRe2Apn9pazWNp68AlFDQ+h3CGdCF7wGN2UVFs6/KF8062DeKUN79Elo3zrvBTR+n9Sjvjkrul3ikG/V4fkzuL+PEDQzucDJdwQSTDkESUwbAqi6Xqzx4oIvmF62oqfDBAFwbZcqh7WaS+1RYpqK3/cCDF30KBe0oIfQDqy4gKpoeKVgpiXuvSw5VF0ecKiqdK6B8re+kSNJYa/GZietZYNXIxJqyi/dHzVgr66/t9XMr6PaQ9YbTUuOHtUwLdXf3ltmJLr15I342cTeMRpWNXWKyRmg3WuB1FiW1TEo09WQhR0EsQ7w5yraaOUpa10TCq5F+dS5oFwPGDPOoYtIXN7nBF0zZrLORjyFH0bQfC5o2QloHhZbYXCYfjihxZg4jXNk//0KJ4cqcGNgAxocIg3MjI3zvctL6XQrxPjbcvQXzzgaFKsJXUShesjwP4aQz2oAFARDbCVM="
  - secure: "Ro/zi18tmNmqjWPEMgEFDEuFw0iqi2KaX6MvIS54v08Ups7AXp0EF605EBZID5GGao3p9/SitIQIFqVZ7OZrfNtJMW3CRyEpOG41uToRuhep6x+Mf2GGuPD4PyTmXWJJUSIfyRKSeCfdiQ88fo0BHu++PtWQqXcHi++OzglREYix05vBzOWuYQOo7692YlrEqBTTSBauZaPVjVxO6dkxDVDyoEyu+n+bPYpdTvJKjng7xeohkxjN0Oa1OU8IMoAEbTbwYJUiTpO7+1Om21u+g/Ps8Jp96AgcvC0yn3GQ00yHpF4Y0MSzu2b9c2wSANWvgX8/u1EqABKqseD6wwul4yciGtZOsLEstNuhOrTUmFwYy0VUiSqku0aQwOjJxdxED9CwDyHdRLQywjFm44XB4UjUEa8WBve0wbR0BWSijgXHv4PPPhXDidwsQOQmZUkpbpKNbmmEYI5TxX2kxAnbZt7I1CLN80+NMNhl9WwKccTprGmYJ7UJIoUiJ8AEsz+pW1bh0gvs3GrnicEVHhbkJ0CLsW/WknrD8152i1pbITLY/acpF2gdofDtnqMoIVycYk62w89L7VwC54evPEpz9q5wPCAUjKabr2UlKf5EeOu35nd5r6n/DNDUOaFn358gOVOZTE9dctqvAtYk5DSCAv86MGAJxBOkofOI8GM5kSQ="

services:
	- docker

deploy:
    provider: script
    script:
      - docker build -t breedbase/pg:$TRAVIS_BUILD_NUMBER .
      - docker tag breedbase/pg:$TRAVIS_BUILD_NUMBER breedbase/pg:latest
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      - docker push breedbase/pg:$TRAVIS_BUILD_NUMBER
      - docker push breedbase/pg:latest
    on:
        branch: master